// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Game
    {
        [DataMember(Name = "Id")]
        public ulong Id;
        [DataMember(Name = "Board")]
        public string Board;
        [DataMember(Name = "Status")]
        public string Status;
        [DataMember(Name = "Player1")]
        public SpacetimeDB.Identity? Player1;
        [DataMember(Name = "Player2")]
        public SpacetimeDB.Identity? Player2;
        [DataMember(Name = "CurrentPlayer")]
        public SpacetimeDB.Identity? CurrentPlayer;

        public Game(
            ulong Id,
            string Board,
            string Status,
            SpacetimeDB.Identity? Player1,
            SpacetimeDB.Identity? Player2,
            SpacetimeDB.Identity? CurrentPlayer
        )
        {
            this.Id = Id;
            this.Board = Board;
            this.Status = Status;
            this.Player1 = Player1;
            this.Player2 = Player2;
            this.CurrentPlayer = CurrentPlayer;
        }

        public Game()
        {
            this.Board = "";
            this.Status = "";
        }
    }
}
