// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateGameHandler(ReducerEventContext ctx);
        public event CreateGameHandler? OnCreateGame;

        public void CreateGame()
        {
            conn.InternalCallReducer(new Reducer.CreateGame(), this.SetCallReducerFlags.CreateGameFlags);
        }

        public bool InvokeCreateGame(ReducerEventContext ctx, Reducer.CreateGame args)
        {
            if (OnCreateGame == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateGame(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateGame : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "CreateGame";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateGameFlags;
        public void CreateGame(CallReducerFlags flags) => CreateGameFlags = flags;
    }
}
