// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MakeMoveHandler(ReducerEventContext ctx, ulong gameId, int position);
        public event MakeMoveHandler? OnMakeMove;

        public void MakeMove(ulong gameId, int position)
        {
            conn.InternalCallReducer(new Reducer.MakeMove(gameId, position), this.SetCallReducerFlags.MakeMoveFlags);
        }

        public bool InvokeMakeMove(ReducerEventContext ctx, Reducer.MakeMove args)
        {
            if (OnMakeMove == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMakeMove(
                ctx,
                args.GameId,
                args.Position
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MakeMove : Reducer, IReducerArgs
        {
            [DataMember(Name = "gameId")]
            public ulong GameId;
            [DataMember(Name = "position")]
            public int Position;

            public MakeMove(
                ulong GameId,
                int Position
            )
            {
                this.GameId = GameId;
                this.Position = Position;
            }

            public MakeMove()
            {
            }

            string IReducerArgs.ReducerName => "MakeMove";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MakeMoveFlags;
        public void MakeMove(CallReducerFlags flags) => MakeMoveFlags = flags;
    }
}
