// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ResetGameHandler(ReducerEventContext ctx, ulong gameId);
        public event ResetGameHandler? OnResetGame;

        public void ResetGame(ulong gameId)
        {
            conn.InternalCallReducer(new Reducer.ResetGame(gameId), this.SetCallReducerFlags.ResetGameFlags);
        }

        public bool InvokeResetGame(ReducerEventContext ctx, Reducer.ResetGame args)
        {
            if (OnResetGame == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnResetGame(
                ctx,
                args.GameId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ResetGame : Reducer, IReducerArgs
        {
            [DataMember(Name = "gameId")]
            public ulong GameId;

            public ResetGame(ulong GameId)
            {
                this.GameId = GameId;
            }

            public ResetGame()
            {
            }

            string IReducerArgs.ReducerName => "ResetGame";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ResetGameFlags;
        public void ResetGame(CallReducerFlags flags) => ResetGameFlags = flags;
    }
}
